name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - new

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v7
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: Update/Pick Submodules
      run: |
        git submodule update --init --recursive --remote
        #git -C AndroidLibXrayLite checkout 5fa2b07
        #git -C hev-socks5-tunnel checkout 50f0019e10c6ad9b12cffe5990712227e9eb811e

    - name: Setup Android SDK
      uses: android-actions/setup-android@v4
      with:
        log-accepted-android-sdk-licenses: false
        cmdline-tools-version: '14742923'
        packages: 'platforms;android-37.0 build-tools;37.0.0 platform-tools'

    - name: Install NDK
      run: |
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
          --channel=0 \
          --install "ndk;29.0.14206865"
        echo "NDK_HOME=$ANDROID_HOME/ndk/29.0.14206865" >> $GITHUB_ENV
        sed -i '17i\
        \
        externalNativeBuild { \
            ndkVersion = "29.0.14206865" \
        }' ${{ github.workspace }}/V2rayNG/app/build.gradle.kts
        sed -i 's/JNI_VERSION_1_4/JNI_VERSION_1_6/g' hev-socks5-tunnel/src/hev-jni.c
            
    - name: Update Version
      id: version
      run: |
        echo "go_version=$(curl -s 'https://go.dev/dl/?mode=json&include=all' | jq -r '.[0].version | sub("^go"; "") | if test("rc[0-9]+$") then capture("^(?<majmin>[0-9]+\\.[0-9]+)(?<rc>rc[0-9]+)$") | "\(.majmin).0-\(.rc | sub("rc"; "rc."))" else . end')" >> $GITHUB_OUTPUT

        Gradle=$(curl -s https://services.gradle.org/versions/current | jq -r '.version')
        sed -i "s|gradle-.*-bin\.zip|gradle-$Gradle-bin.zip|" "${{ github.workspace }}/V2rayNG/gradle/wrapper/gradle-wrapper.properties"    
    
    - name: Setup Golang
      uses: actions/setup-go@v6
      with:
        go-version: ${{ steps.version.outputs.go_version }}
        cache: false

    - name: Patch Go
      run: |
        goversion=$(go version | awk '{print $3}')
        go_ver=$(echo "$goversion" | sed -E 's/^go([0-9]+\.[0-9]+).*/\1/')
        branch="release-branch.go${go_ver}"
        diff_url="https://github.com/golang/go/compare/$goversion...$branch.diff"
        echo "Branch: $branch"
        echo "Diff URL: $diff_url"
        if curl -sL "$diff_url" | grep -q '^diff'; then
          cd "$(go env GOROOT)" && curl -sL "$diff_url" | patch -p1
        fi

    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Restore cached libhevtun
      id: cache-libhevtun-restore
      uses: actions/cache/restore@v6
      with:
        path: ${{ github.workspace }}/libs
        key: libhevtun-${{ runner.os }}-${{ env.NDK_HOME }}-${{ hashFiles('.git/modules/hev-socks5-tunnel/HEAD') }}-${{ hashFiles('compile-hevtun.sh') }}

    - name: Build libhevtun
      if: steps.cache-libhevtun-restore.outputs.cache-hit != 'true'
      run: |
        bash compile-hevtun.sh

    - name: Save libhevtun
      if: steps.cache-libhevtun-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v6
      with:
        path: ${{ github.workspace }}/libs
        key: libhevtun-${{ runner.os }}-${{ env.NDK_HOME }}-${{ hashFiles('.git/modules/hev-socks5-tunnel/HEAD') }}-${{ hashFiles('compile-hevtun.sh') }}

    - name: Copy libhevtun
      run: |
        cp -r ${{ github.workspace }}/libs ${{ github.workspace }}/V2rayNG/app    

    - name: Build AndroidLibXrayLite
      run: |
        bash libxray.sh
        cp ${{ github.workspace }}/AndroidLibXrayLite/*.aar ${{ github.workspace }}/V2rayNG/app/libs/

    - uses: gradle/actions/setup-gradle@v6

    - name: Build APK
      run: |
        cd ${{ github.workspace }}/V2rayNG
        echo "sdk.dir=${ANDROID_HOME}" > local.properties
        echo "TAG=$(grep 'versionName =' ./app/build.gradle.kts | sed 's/.*versionName = "\(.*\)"/\1/')" >> $GITHUB_ENV
        chmod 755 gradlew
        #./gradlew licenseFdroidReleaseReport
        ./gradlew assembleRelease --build-cache --parallel --daemon --warning-mode all

    - name: Delete releases and workflows runs
      uses: ophub/delete-releases-workflows@main
      with:
        delete_releases: true
        releases_keep_latest: 0
        delete_tags: true
        delete_workflows: true
        workflows_keep_day: 0
        gh_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload to release
      uses: softprops/action-gh-release@v3
      with:
        draft: false
        files: |
          ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/*/release/*v8*.apk
          ${{ github.workspace }}/xray-core.tar.gz
          ${{ github.workspace }}/xraylite_android.tar.gz
        tag_name: ${{ env.TAG }}
